import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { AccountDetailsModalProvider } from "@/components/providers/AccountDetailsModalProvider";
import AccountDetailsModal from "@/components/account-details/AccountDetailsModal";
import { NoVehicleErrorModalProvider } from "@/components/providers/NoVehicleErrorModalProvider"; // Nuevo import del Provider
import NoVehicleErrorModal from "@/components/NoVehicleErrorModal"; // Nuevo import del componente del modal

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TowIt: Towers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <AccountDetailsModalProvider>
            <NoVehicleErrorModalProvider> {/* Nuevo proveedor */}
              {children}
              <AccountDetailsModal />
              <NoVehicleErrorModal /> {/* Nuevo modal */}
            </NoVehicleErrorModalProvider>
          </AccountDetailsModalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
