import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { AccountDetailsModalProvider } from "@/components/providers/AccountDetailsModalProvider"; // Importar el Provider
import AccountDetailsModal from "@/components/account-details/AccountDetailsModal"; // Importar el componente del modal

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TowIt: Towers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <AccountDetailsModalProvider>
            {children}
            <AccountDetailsModal /> {/* Renderizar el modal al final del body */}
          </AccountDetailsModalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
